
#!/bin/bash
#PBS -N PottsBench
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=1
#PBS -m abe
#PBS -M leonardo.romor@gmail.com

cd /home/lromor/Potts_code/bench/parameters_sweeping

#NORMAL
module purge
module load gnu/4.9.2
source /u/shared/programs/x86_64/intel/parallel_studio_xe_2015/composer_xe_2015.0.090/bin/iccvars.sh intel64

#MPI
# module load openmpi/1.8.3/intel/14.0
# module unload intel
# module load gnu/4.9.2
# source /u/shared/programs/x86_64/intel/parallel_studio_xe_2015/composer_xe_2015.0.090/bin/iccvars.sh intel64


make bench
