
#!/bin/bash
#PBS -N PottsBench
#PBS -l walltime=10:00:00
#PBS -l nodes=4:ppn=20
#PBS -m abe
#PBS -M leonardo.romor@gmail.com

cd /home/lromor/Potts_code/ulisse/testing_ht

module purge

module load openmpi/1.8.3/intel/14.0
module unload intel
module load gnu/4.9.2
source /u/shared/programs/x86_64/intel/parallel_studio_xe_2015/composer_xe_2015.0.090/bin/iccvars.sh intel64

make

module purge
module load openmpi/1.8.3/intel/14.0

:>data.txt

for opt in none core socket
do
    for j in 2 4 8 10 16 20
    do
        mpirun --bind-to $opt -np $j ./main.x $(($j-1)) >> ${opt}_data.txt
    done
done
